### ISSUE TITLE
[Bug] Crashes Anki on macOS when trying to commit html changes.

### ISSUE THREAD

**Issue by kvn1351** [ijgnd/anki__editor_edit_html_extended#6]
Hi, first of all, thanks for this excellent addon! Unfortunately, when I press ok, i.e. want to commit the changes, it crashes Anki.

The current workaround is to just copy everything from the editor and paste it into the OG Anki editor :/

System info and the crash log are attached below.

![CleanShot 2022-09-09 at 15 43 58](https://user-images.githubusercontent.com/11823348/189364364-855d6a3c-2784-46f9-a56b-4d6953b297e4.png)

Version Info |
------ |
macOS Monterey |
Version 12.4 |
Version ⁨2.1.54 (b6a7760c) ⁩|
Python 3.9.7 Qt 6.3.1 PyQt 6.3.1 |

MacOS crash report:
https://pastebin.com/iHPwtafy

**Comment by kvn1351** [comment]
~~I think that I've found the issue. It seems to be `sync_execJavaScript()`. I guess that this is qt6 related.~~

Edit: Nope, it works fine.

**Comment by kvn1351** [comment]
It took me 1h+ to debug but alas, here it is:

https://github.com/ijgnd/anki__editor_edit_html_extended/blob/42fa6922527d47a7f450ea53301ec49e8ef481de/src/dialog_cm.py#L251

This line is causing the segfault. Since it's not needed for the template editor I've just commented it out.
I don't understand why this string replacement even happens for the template dialog. Perhaps there's a reason I'm not aware of.

Either way, now you've got it easier than a cryptic segfault :)

Thanks once more for this addon.

**Comment by ijgnd** [comment]
thanks for reporting this and posting the solution. I removed the two lines and uploaded a new version to ankiweb. 

I had this code because I originally tried to sync back the cursor position from tinymce into anki. But I've removed this functionality a long time ago. I forgot to remove these lines.

If I broke something else with this new release let me know. Other improvements are also highly welcome.
